// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcyut2kkeZlgrY6inAItIJo-sQ8Q-hgs',
    appId: '1:563312667179:web:e7ffc841e65a16d8fcd86e',
    messagingSenderId: '563312667179',
    projectId: 'fruits-hub-8b27a',
    authDomain: 'fruits-hub-8b27a.firebaseapp.com',
    storageBucket: 'fruits-hub-8b27a.firebasestorage.app',
    measurementId: 'G-R3Y8B9DBYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiTy6Z3ekYx9prHTKT8PKjZXWzEqq5Xls',
    appId: '1:563312667179:android:4f92ff8897b10636fcd86e',
    messagingSenderId: '563312667179',
    projectId: 'fruits-hub-8b27a',
    storageBucket: 'fruits-hub-8b27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYDVo1ESNOijJ69CnGP57EXPH9p9VDsng',
    appId: '1:563312667179:ios:e49bbaecf569f907fcd86e',
    messagingSenderId: '563312667179',
    projectId: 'fruits-hub-8b27a',
    storageBucket: 'fruits-hub-8b27a.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYDVo1ESNOijJ69CnGP57EXPH9p9VDsng',
    appId: '1:563312667179:ios:e49bbaecf569f907fcd86e',
    messagingSenderId: '563312667179',
    projectId: 'fruits-hub-8b27a',
    storageBucket: 'fruits-hub-8b27a.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVcyut2kkeZlgrY6inAItIJo-sQ8Q-hgs',
    appId: '1:563312667179:web:f59983f1df527e3dfcd86e',
    messagingSenderId: '563312667179',
    projectId: 'fruits-hub-8b27a',
    authDomain: 'fruits-hub-8b27a.firebaseapp.com',
    storageBucket: 'fruits-hub-8b27a.firebasestorage.app',
    measurementId: 'G-0HR2M3ZSJD',
  );
}
